/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.noisruker.locodrive;

import org.checkerframework.checker.units.qual.A;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());

        AddressArg address = new AddressArg(16);
        assertEquals("AddressArg", 16, address.address());
    }
}
